version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  runner:
    build: .
    ports:
      - "5555:5555"
    environment:
      - BROKER=redis://redis:6379/0
    depends_on:
      - redis
